# Generated by Django 5.0.3 on 2024-03-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='precio',
            field=models.PositiveSmallIntegerField(max_length=12),
        ),
    ]
