# Generated by Django 5.0.3 on 2024-03-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_alter_presupuesto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='manoDeObra',
            field=models.IntegerField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='materiaPrima',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='titulo',
            field=models.CharField(default=2, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
