# Generated by Django 5.0.3 on 2024-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_alter_presupuesto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
