# Generated by Django 5.0.3 on 2024-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_remove_presupuesto_done_alter_presupuesto_manodeobra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='manoDeObra',
            field=models.IntegerField(),
        ),
    ]
